### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [GrakovNe/lissen-android#23]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/8238894283#L516

as we don't have Java 19 in Debian: https://packages.debian.org/search?suite=all&arch=amd64&searchon=names&keywords=openjdk-19-jdk-headless

Can the app be built with 17 or 21 maybe?

**Comment by GrakovNe** [comment]
21 shall be ok to build it with 19 target

**Comment by GrakovNe** [comment]
@licaon-kter after https://github.com/GrakovNe/lissen-android/commit/fed80dcac31ac9cbdc9dd50e558c3e0bcb9ef4c9 you may restart the build

**Comment by licaon-kter** [comment]
Thanks
