### ISSUE TITLE
If there is no cover set on a book, lissen will play the "loading" animation forever, which is irritating

### ISSUE THREAD

**Issue by kuldan5853** [GrakovNe/lissen-android#39]

**Comment by GrakovNe** [comment]
Could you please try out the latest one release: https://github.com/GrakovNe/lissen-android/releases/tag/1.0.23

I have fixed the similar bug

If it still could be reproduced, would you like to share with me access to your ABS for a short time. That's incredible simplifies the research. You may just create separated account with the problem book and share the credentials to grakovne@gmail.com or to Discord: @grakovne

Thank a lot for the issue!

**Comment by GrakovNe** [comment]
![IMAGE 2024-11-07 01:34:57](https://github.com/user-attachments/assets/d6a6d269-3e5a-4083-9874-1e2abe09fc19)

That's why I'm asking. There doesn't appear to be a described bug, as you can see in the screenshot. However, there must be a **different** kind of bug, and it seems that further investigation is required

**Comment by kuldan5853** [comment]
Seems to work fine for me in .33 (had .31 before) - I'm now seeing the placeholder image instead of the loading animation.

**Comment by GrakovNe** [comment]
Glad to hear that the bug has been fixed technically before you did create the issue xx

Anyway, great thanks for the reporting a problem, it makes me happy that someone cool using this app

**Comment by kuldan5853** [comment]
> Anyway, great thanks for the reporting a problem, it makes me happy that someone cool using this app

I'm also helping with the official ABS app, I just like this project quite a bit :)

Your app has a long way to go, but I like the general approach and the flutter based code, so I'm following your progress :)

I think when you have full library browsing (authors/series/collections) in I can actually start using it to play some books during my normal routine.
