### ISSUE TITLE
Blank screen when primary library is a podcast library

### ISSUE THREAD

**Issue by GrakovNe** [GrakovNe/lissen-android#43]
If on the ABS server you set your top listed library as a podcast library then when opening Lissen it just won't show anything (blank screen). While podcasts aren't supported yet, Lissen should see if there's a non-primary library on the ABS server that has audiobooks. I worked around this by making audiobooks my primary, but it took a bit to figure out what was wrong.

Source: https://www.reddit.com/r/audiobookshelf/comments/1gc1xei/comment/lw98brg/

**Comment by Apprentice57** [comment]
I probably should've just gone to github's issues here directly. Thank you for addressing this!

**Comment by GrakovNe** [comment]
Glad to inform that the issue was fixed into https://github.com/GrakovNe/lissen-android/releases/tag/1.0.26 release.

@Apprentice57 Would you like to check it please?

**Comment by Apprentice57** [comment]
> Glad to inform that the issue was fixed into https://github.com/GrakovNe/lissen-android/releases/tag/1.0.26 release.
> 
> @Apprentice57 Would you like to check it please?

Worked well for me with this fix!

**Comment by GrakovNe** [comment]
Thank you for the cooperation!
