### ISSUE TITLE
Server url ext field not tagged as URI

### ISSUE THREAD

**Issue by Freizan** [GrakovNe/lissen-android#45]
In the login screen the field for the URL of the server is missing a tag for the keyboards to not autocorrect the content.

**Comment by Freizan** [comment]
PR created : https://github.com/GrakovNe/lissen-android/pull/46

**Comment by GrakovNe** [comment]
Thank you so much! Your PR has been merged into the master branch and released here: [v1.0.27](https://github.com/GrakovNe/lissen-android/releases/tag/1.0.27).

Thanks again for your contribution—it’s much appreciated!
