### ISSUE TITLE
After the update can't see old downloads

### ISSUE THREAD

**Issue by Frumkin13** [GrakovNe/lissen-android#47]
Hello, love your app,but found a weird thing.So,the problem is that after update from 1.0.24 to 1.0.27 can't see old downloaded books.When i connect to server i can see that they are downloaded,but in offline mode no books are available.I guess i can redownload but i hope it will be possible to make them visible after update.Thanks for your work!

**Comment by GrakovNe** [comment]
Hello! Thanks for the kind words and for bringing this issue to my attention. I did some research and found that the app was inconsistently verifying the integrity of cached files when loading data—some files were checked, while others weren’t. I’ve now added consistent checks to ensure that partially cached books won’t appear in the list.

This should prevent the issue in future updates. For now, I recommend clearing the app cache and re-downloading your books to resolve any data inconsistencies. After doing this, everything should work smoothly. Thanks again for reporting this!

Release with the fix: https://github.com/GrakovNe/lissen-android/releases/tag/1.0.28
