### ISSUE TITLE
[Feature Request] Sleep timer

### ISSUE THREAD

**Issue by WisdomCode** [GrakovNe/lissen-android#48]
Thank you for developing the app, I like the very minimal and sleak design!

I think there is a large userbase of audiobook users that listen to them while trying to sleep. For this reason, many players have an inbuilt timer that can be activated. If that timer goes to zero, the audiobook goes to pause, guaranteeing you do not loose the current position because you fell asleep and the book ran through the night for hours.
This feature, if made sophisticated enough, also features: 
1. An intuitive function, normally shaking the phone, to reset the timer without interacting with a bright screen or needing to unlock the phone. A quick vibration provides haptic feedback that the reset took place.
2. In combination with that, the audiobook fades out in the last, say 10 seconds, so the user can in turn react if the timer is to be reset.

**Comment by GrakovNe** [comment]
Hi! Thanks for suggesting the timer feature! 

It’s confirmed and planned for implementation soon, right after i wrap up work on the podcast feature. I’ll keep this issue open so we can track its progress.

Thanks again for the great idea, and stay tuned!

**Comment by GrakovNe** [comment]
The very first, basic implementation of the timer feature has been added in version 1.1.4: https://github.com/GrakovNe/lissen-android/releases/tag/1.1.4
