### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sundarprasad139** [GrakovNe/lissen-android#55]
To add local audio book files / folders

**Comment by GrakovNe** [comment]
Do you mean opportunity to store books on the phone directly in some folders and play it through Lissen App?

**Comment by GrakovNe** [comment]
Thank you for your suggestion! However, Lissen is primarily designed as a client for Audiobookshelf, and the app has been built specifically with this integration in mind. While adding support for local audiobook files or folders is technically possible, it falls outside the scope and goals of this project.

I appreciate your understanding, and I'm always open to feedback related to improving Lissen as an Audiobookshelf client. Thank you for your interest in the app!

**Comment by sundarprasad139** [comment]
> Do you mean opportunity to store books on the phone directly in some folders and play it through Lissen App?

Yes and also books that are already present in phone storage (not downloaded from Lissen App)
