### ISSUE TITLE
Удаляются книги из кэша 

### ISSUE THREAD

**Issue by Frumkin13** [GrakovNe/lissen-android#57]
Приветствую, надеюсь тут можно по-русски писать,судя по телеграму Вы понимаете :). Приложение отличное,еще раз спасибо!А теперь к делу,суть в чем:
Версия приложения 1.1.3,на всякий уточню,и уже несколько раз у меня удалялись книги:Сначала после обновления с версии 1.1.1, теперь вот еще раз(точно не знаю когда,т.к. пару дней не слушал).Мне кажется,что это из-за очистки кэша,которую я иногда делаю, поэтому вопрос:Можно сделать так,чтобы книги хранились в каком-то месте,где не будут удаляться с кэшем?А то не очень удобно каждый раз их скачивать, чтобы послушать на улице.Хотя, может это какой-нибудь баг,и дело не в кэше.Надеюсь поможете,а то приложение крутое и хочется дальше им пользоваться с комфортом,а так есть страх,что перед выходом нужных книг под рукой может не оказаться.В любом случае спасибо за труд!

**Comment by GrakovNe** [comment]
Привет!

Починим :-)

спасибо что написал!

**Comment by GrakovNe** [comment]
@Frumkin13 расскажите пожалуйста, как проявляется проблема? книги исчезают только после того как вы удаляете кеш или при каждом обновлении приложения?

**Comment by Frumkin13** [comment]
> @Frumkin13 расскажите пожалуйста, как проявляется проблема? книги исчезают только после того как вы удаляете кеш или при каждом обновлении приложения?

Здравствуйте,да вот не знаю точно...Вчера пробовал на 1.1.3 удалять из кэша - все было на месте (размер был около 570мб),потом обновился до 1.14 и 1.1.5, спустя какое-то время зашёл и ничего нет.Я сразу не проверил, так что точно сказать не могу,видимо стоит после следующего обновления глянуть.Тут мало что можно рассказать,но если нужно что-то уточнить - спрашивайте, постараюсь ответить!

**Comment by Frumkin13** [comment]
А,ну и после обновления опять скачал кое-что, сейчас еще раз кэш очистил - тоже на месте.Не уверен,но мне кажется,что это связано с обновлениями,либо кэш сам куда то исчезает по прошествии времени.

**Comment by Frumkin13** [comment]
День добрый,сейчас обновился до 1.1.6 и пока все на месте после обновления,буду дальше следить за этим всем.

**Comment by Frumkin13** [comment]
@GrakovNe Опять это случилось,но после перезагрузки,я решил на всякий случай проверить и оно все исчезло.Было 450мб,стало 70мб.Похоже что-то при перезагрузке удаляет эти файлы,об этом я до этого не думал.Я 2 раза проверил и оба раза пропало все,видимо дело в этом.Надеюсь это поможет решить проблему

**Comment by GrakovNe** [comment]
расскажите пожалуйста, как вы обновляетесь? вы ставите приложение из одного источника или меняете сторы от версии к версии?

**Comment by Frumkin13** [comment]
> расскажите пожалуйста, как вы обновляетесь? вы ставите приложение из одного источника или меняете сторы от версии к версии?
Добрый день, изначально нашел Ваше приложение через F-Droid,затем обновлял через Obtainium с гитхаба,т.к. у меня рутированное устройство я не удалял ту версию,если мне не изменяет память.Думаете в этом причина?

**Comment by GrakovNe** [comment]
да. Android работает таким образом, что хранилище данных при приложении принадлежит конкретному приложению, причем идентификатором является ключ подписи. Поскольку релизные пакеты приложения у Lissen подписываются разными ключами для google play / rustore / f-droid (который использует свою систему сборки параллельную моей), то с точки зрения OS это разные приложения и они не могут шарить друг с другом свои кешированные данные. Отсюда и перетирания и необходимость перелогина на сервер после установки из другого источника

Рекомендую выбрать какой хотите канал обновлений (GPlay получает изменения с дневной задержкой, F-Droid - с трехдневной, Rustore и релиза гитхаба - мгновенно) и попробовать установив приложение начисто не менять этот канал

В будущем я добавляю воспроизводимые билды чтобы подписывать все копии APK одним ключом, но не сегодня

**Comment by Frumkin13** [comment]
> да. Android работает таким образом, что хранилище данных при приложении принадлежит конкретному приложению, причем идентификатором является ключ подписи. Поскольку релизные пакеты приложения у Lissen подписываются разными ключами для google play / rustore / f-droid (который использует свою систему сборки параллельную моей), то с точки зрения OS это разные приложения и они не могут шарить друг с другом свои кешированные данные. Отсюда и перетирания и необходимость перелогина на сервер после установки из другого источника
> 
> Рекомендую выбрать какой хотите канал обновлений (GPlay получает изменения с дневной задержкой, F-Droid - с трехдневной, Rustore и релиза гитхаба - мгновенно) и попробовать установив приложение начисто не менять этот канал
> 
> В будущем я добавляю воспроизводимые билды чтобы подписывать все копии APK одним ключом, но не сегодня

Понял, спасибо за помощь! Установлю тогда с гитхаба, надеюсь больше не будет этой проблемы.Думал это баг какой,а оказалось, что все гораздо проще... Раньше таких проблем с другими приложениями не было, поэтому не думал,что это может быть причиной.Еще раз благодарю за внимание к моей проблеме! Успехов Вам и надеюсь не забросите приложение :)

**Comment by GrakovNe** [comment]
я подержу тикет отворенным, если заметите инконсистетность кеша еще - напишите пожалуйста

**Comment by Frumkin13** [comment]
@GrakovNe Знаете, как-то мне не помогла переустановка,что сделал:
1.Удалил старую версию 
2.Поставил заново с гитхаба, скачал книги,перезагрузил - все пропало
3.Удалил еще раз версию на всякий и просто перезагрузил
4.Поставил еще раз с гитхаба, скачал книги,перезагрузил - все опять пропало
Вроде сделал как Вы сказали,а результат все тот же,к сожалению :(

**Comment by GrakovNe** [comment]
я пока не понимаю источник проблемы и у меня не получается воспроизвести поведение. Книги совершенно точно удалятся из памяти, если почистить кеш приложения, это ожидаемое поведение

Но если вы этого не делаете, расскажите пожалуйста какой у вас телефон и какие изменения вы вносили в систему кроме рут-доступа

**Comment by Frumkin13** [comment]
@GrakovNe Приветствую,сразу скажу,что,когда я вручную удаляю кэш в меню "О приложении" вес приложения не уменьшается,так что таким образом они,вроде не пропадают.У меня телефон Xiaomi redmi note 5 MIUI 13 Android 12(Портированная прошивка).Изменений глобальных особо и не было,кроме тех что назвал.
Тут вот какое дело:У меня кроме Вашего приложения стоят и другие,например: [Официальный мобильный клиент](https://github.com/advplyr/audiobookshelf-app) последней версии,в котором контент у меня не удаляется после перезагрузки девайса. Мне кажется,я знаю в какую сторону нужно смотреть.До этого я другое писал,но кое-что выяснил пока проверял.В моем телефоне есть приложение загрузки,в котором отображаются загруженные мною файлы,и Ваше приложение почему-то тоже отображает загрузку книг через него как непонятного расширения файлы(скрин прикладываю).Но вот после перезагрузки телефона эти непонятные файлы исчезают из списка и,соответственно,из памяти устройства.Возможно,система удаляет непонятные для нее файлы,с которыми не знает что делать.Официальное приложение качает каким-то образом в обход приложения загрузки,поэтому кэш отлично держится даже после перезагрузки телефона.Видимо это какие-то особенности MIUI,о которых я не знаю,т.к я не разработчик,а обычный пользователь.Мне гораздо больше нравится Ваше приложение,поэтому я очень не хочу использовать оригинал,и надеюсь Вы сможете решить проблему.Может это поможет не только мне,но и другим пользователям MIUI,если это действительно как-то связано,Спасибо,что уделяете этой проблеме время!
![Screenshot_2024-11-23-15-21-50-062_com android providers downloads ui](https://github.com/user-attachments/assets/1f85d7f9-43c3-4f4c-89ed-b60717d5b432)

**Comment by GrakovNe** [comment]
после многих обновлений и полного переписывания движка сохранения книг в память, я не могу ни воспроизвести проблему, ни убедиться что дело в приложении вообще. Я проверил теории которые вы предлагаете выше, но не могу утверждать что они имеют отношение к реальности

Существует связанный баг https://github.com/GrakovNe/lissen-android/issues/90 с сохранением книг в память, но он возникает при попытке вгрузить книги, а не после обновления

Я пока хотел бы закрыть тикет в рамках груминга беклога, если вы сможете воспроизвести поведение на другом устройстве с максимально стандартным андройдом (в идеале на Pixel устройствах) - я смогу чем-то помочь!

с наступающим!
