### ISSUE TITLE
Feature Request: Widgets

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [GrakovNe/lissen-android#59]
A homescreen widget would be extremely useful.

**Comment by GrakovNe** [comment]
Great. Thank you much for the report, it'll be implemented soon

**Comment by GrakovNe** [comment]
very first and naive implementation of the widget has been implemented in https://github.com/GrakovNe/lissen-android/releases/tag/1.1.9

![2024-11-21 20 01 19](https://github.com/user-attachments/assets/30634e30-95ee-4b77-98c4-2ce47c4aaeae)

Feel free to try it it
