### ISSUE TITLE
Podcast Order/Duration Issues

### ISSUE THREAD

**Issue by kar731** [GrakovNe/lissen-android#60]
Hi, thank you for working on Lissen! I have been exclusively using Lissen over the default audiobookshelf app due to it auto-sorting podcasts from oldest -> newest and have been loving it. I solely listen to Audiodramas so the order being Old -> Newest is very important to me so I can listen to the story easily, but there are currently some small issues with it for me.

Most of my podcasts are in the correct order, but a select few are either New -> Old or with some in the wrong order. (When they are in the wrong order Lissen refuses to play those episodes for some reason despite them working on regular ABS)
![image](https://github.com/user-attachments/assets/7826f00a-418f-40fd-9980-cb5d66cf4a18)
![image](https://github.com/user-attachments/assets/a93ac54f-29f4-4016-afa9-d88a79e4b04b)

In addition to that, sometimes when finishing an episode on Lissen and going to the next it marks the finished episode as in-progress and having hours left when you visit the Audiobookshelf webplayer (I'm also on the latest ABS version).

![image](https://github.com/user-attachments/assets/6fdb2922-c641-4708-ac26-71eb52034c36)
![image](https://github.com/user-attachments/assets/f7d39d2b-f038-46c0-ae3a-166d3a4dd9b3)

It would also be great if you could implement an option for archiving/hiding watched episodes! 

I am using a Pixel 6 Pro on Android 14 on the latest Lissen version 1.1.7. These issues do not occur when using the regular ABS app/webplayer. Other than these issues I am loving the app and thank you!

**Comment by GrakovNe** [comment]
Thank you for your feedback and for reporting these issues!

Regarding the inconsistency with playback progress syncing, I’ve created a separate task to address this problem. You can follow the progress here: https://github.com/GrakovNe/lissen-android/issues/61

As for the sorting issue, podcasts in Lissen are intended to sort from oldest to newest. If this is not working correctly for some of your podcasts, could you please share credentials for a test account with access to one of the problematic podcasts? This will allow me to investigate the issue more thoroughly. If you’re comfortable, you can email me directly at grakovne@gmail.com.

Thank you again for your detailed report!

**Comment by GrakovNe** [comment]
Also, could you try the latest one release https://github.com/GrakovNe/lissen-android/releases/tag/1.1.8, it contains the fix related to the podcast episode ordering

**Comment by GrakovNe** [comment]
Thank you much!

You always may reach me via email or by creating the new one issue!
