### ISSUE TITLE
Using the SD card for offline

### ISSUE THREAD

**Issue by IcedQuinn** [GrakovNe/lissen-android#79]
On devices which still permit the use of SD cards (tablets) it would be nice to be able to use them to store the offline cache.

I have a small tablet with 32gb onboard storage (with about 10gb left after the OS & applications) but has a 256gb external memory card.

**Comment by GrakovNe** [comment]
Thank you for your suggestion! Unfortunately, this feature is not planned, as devices with external SD cards are becoming increasingly rare. Investing time in supporting a technology that is gradually phasing out would mean delaying or foregoing features that are more universally needed. However, if this is important to you, you're welcome to contribute by submitting a pull request—we’d be happy to review it!

**Comment by IcedQuinn** [comment]
> as devices with external SD cards are becoming increasingly rare.

i mean, no? this is true mostly for direct-to-ewaste cell phones. the SD slot is very much alive in even budget tablets, specialty phones, and DAPs, all which run android and f-droid. 

- https://www.audiophile-heaven.com/2024/01/hiby-digital-m300-android-dap-new-pocketable-music-flavour.html
- https://www.lenovo.com/us/en/p/tablets/android-tablets/lenovo-tab-series/lenovo-tab-m9-9-inch-mtk/len103l0016
- https://store.planetcom.co.uk/products/cosmo-communicator
- https://www.unihertz.com/products/jelly-max
- https://shop.boox.com/collections/all/products/leaf2

> Investing time in supporting a technology that is gradually phasing out 

if you were writing files to anywhere at all but app cache, scoped storage is the current API to negotiate those permissions. it also entirely abstracts where the permitted folder is.

this is about as dumb as saying because cheap garbage phones are pushing cloud storage you might as well treat the hard drive as deprecated and not download files at all.

> However, if this is important to you,

no, but i'll go donate to Voice which already uses the correct system APIs, thanks.

**Comment by GrakovNe** [comment]
Your tone comes across as aggressive, which doesn’t foster constructive discussion. Open source operates on the principle of voluntary contribution—anyone is welcome to submit a pull request rather than demanding work from the maintainer.

That said, I value your opinion and perspective regardless of the tone. Best of luck with using Voice or any other application that fits your needs.

**Comment by KvIKtIFvMN** [comment]
> Unfortunately, this feature is not planned, as devices with external SD cards are becoming increasingly rare. Investing time in supporting a technology that is gradually phasing out would mean delaying or foregoing features that are more universally needed. 

It may not seem like it but this is an accessibility issue. Until this feature is implemented you are essentially telling people with older devices (who may or may not be in a position legally or financially to acquire a new one) that they can not use your app.  Your gatekeeping your app to only the lucky segment of the population that can afford devices with large amounts of storage space on their primary devices. Its not even necessarily an issue of monetary cost, some people cant switch away from their existing device for other reasons, like needing to use a specific device for work or needing to use a specific brand with compatibility with specific hardware. 

Implementing an option to allow users to choose where lissen stores downloaded files with SAF (which is usually how I see such this kind of thing implemented) has benefits beyond just accessibility. It increases portability (great for backups) and allows users to interact with the podcast files using other apps.

**Comment by GrakovNe** [comment]
@KvIKtIFvMN 

With respect, the considerations you outline are not part of the project’s objectives. I am not focused on ensuring equal access for users regardless of income level. I am not concerned with ecological or “green” motivations that may lead some individuals to voluntarily retain older hardware. I am likewise not addressing personal or sentimental preferences for legacy devices.

Lissen is being developed as a modern audiobook client for contemporary mobile phones. Its feature set, performance profile, and roadmap are aligned with that target platform.

Now that my position regarding the use of older mobile devices in 2025 is clear, and given that I am not focused on questions of income equality, let me add the following.

Lissen is an open-source product. This means that any user, within their abilities and interest, can implement the functionality that they personally require.

If such a contribution does not conflict with the core vision of the application, provides a reliable, stable, and concise UX that is clear to other users, and if the codebase is extensible, maintainable, and readable, I will be glad to accept the merge request into the main branch, release it, and credit the contributor accordingly.

Please let us not confuse custom, requirement-driven development with an open-source project maintained in personal, non-working hours to provide stable and dependable access to audiobooks.

Thank you.
