### ISSUE TITLE
No bottom bar

### ISSUE THREAD

**Issue by davideb263** [GrakovNe/lissen-android#83]
I don't have the bottom bar. The one with library, chapters, speed and preferences like shown in the screenshots. 
I'm using a nothing phone 2 with android 14 and Audiobookshelf version 2.17.5

Please tell me what additional info I can provide to help figuring out the issue.

**Comment by davideb263** [comment]
Sorry I think I misunderstood the screenshots and thought there were a bottom bar also on the homepage. 
I expected to be there because I didn't find a way to change the library without changing the default one in preferences. Maybe I'm missing something or is this the expected behaviour ?

**Comment by GrakovNe** [comment]
Yes, it's the only way to change the preferred library. I've planned some more simple method to handle it (it may be multi-libraries on the same screen or just toggle on the main screen) but it isn't implemented for now

**Comment by davideb263** [comment]
Thank you. Should I close this or leave it open changing the title and rephrasing a bit?

**Comment by GrakovNe** [comment]
No worries, I'll handle it
