### ISSUE TITLE
[FR] Translations?

### ISSUE THREAD

**Issue by thehijacker** [GrakovNe/lissen-android#85]
There aren't that many strings but I would still like to have application in my native language. Can Lissen be translated?

Thanks.

**Comment by GrakovNe** [comment]
Yes, it **shall** be translated

Now, it supports my own language and Englisn

To help improve translations in your native language, you can use [Weblate](https://hosted.weblate.org/projects/lissen/android-app/) and provide some string translations.

If you can’t find your language in the list and can’t add it yourself, let me know, and I’ll add it for you.

**Comment by GrakovNe** [comment]
Po vašem delu sodeč je vaš materni jezik slovenščina!

Pozdrav iz Beograda v tem primeru! Sem Rus, a zadnjih nekaj mesecev živim v Srbiji

Zelo lepo je videti željo po lokalizaciji aplikacije!

**Comment by thehijacker** [comment]
> Po vašem delu sodeč je vaš materni jezik slovenščina!
> 
> Pozdrav iz Beograda v tem primeru! Sem Rus, a zadnjih nekaj mesecev živim v Srbiji
> 
> Zelo lepo je videti željo po lokalizaciji aplikacije!

Tako je. Iz Slovenije. Lep pozdrav tudi tebi.

Just checked weblate project. I can see Slovenian language but there are no strings to translate. Please check.

**Comment by GrakovNe** [comment]
my bad

shall be fixed now: 
<img width="1298" alt="image" src="https://github.com/user-attachments/assets/4c7f1a9f-7765-4e65-a905-877c6e2c5796" />

**Comment by thehijacker** [comment]
All OK now. Will try to finish today. And another vote for good working Android Auto support.

**Comment by thehijacker** [comment]
100 % translated. Will keep an eye for new version so I can test the translations. Might need to improve some.

**Comment by GrakovNe** [comment]
Done in https://github.com/GrakovNe/lissen-android/releases/tag/1.1.23.

You can wait several hours for this release to reach Google Play, or you can download the APK from the release assets now.

Thank you so much for this contribution! I really love multilingual apps!

![2024-12-19 18 24 47](https://github.com/user-attachments/assets/c39ddd08-6358-4f77-b9eb-ce2eba8a58e0)

**Comment by GrakovNe** [comment]
@eskiiom done: https://hosted.weblate.org/browse/lissen/android-app/fr/

**Comment by eskiiom** [comment]
Completed 👍
Have a nice evening !

**Comment by GrakovNe** [comment]
@eskiiomt done in https://github.com/GrakovNe/lissen-android/releases/tag/1.1.24 

Merci beaucoup! 

GP and F-Droid releases be ready soon

![telegram-cloud-photo-size-2-5415858064545933832-y](https://github.com/user-attachments/assets/2064b048-41ea-441c-938d-13756636330b)

**Comment by eskiiom** [comment]
You are very welcome

**Comment by GrakovNe** [comment]
these localization was released and available on GP/FDroid/etc. Now i closing this issue, if someone is so kind to bring another language it's very welcome
