### ISSUE TITLE
Search the book in the library

### ISSUE THREAD

**Issue by GrakovNe** [GrakovNe/lissen-android#9]

**Comment by GrakovNe** [comment]
Done in https://github.com/GrakovNe/lissen-android/releases/tag/1.0.12

**Comment by ecker00** [comment]
Guess this is not published yet (F-Droid)? Really liking the app, but browsing the endless scroll is hard on a large library. Great to see search feature implemented!

**Comment by GrakovNe** [comment]
Why yes, it was published this morning: [F-Droid](https://f-droid.org/en/packages/org.grakovne.lissen/).

I also received the review results on Google Play, and the app is published there as well: [Google Play](https://play.google.com/store/apps/details?id=org.grakovne.lissen), though it’s an older version.
